apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-market
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for demo applications
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the demo-store namespace in the same cluster
  destinations:
  - namespace: demo-store
    server: https://kubernetes.default.svc
  - namespace: demo-wrapper
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceBlacklist:
  - group: ''
    kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  #roles:
  #- name: read-only
  #  description: Read-only privileges to my-project
  #  policies:
  #  - p, proj:my-project:read-only, applications, get, my-project/*, allow
  #  groups:
  #  - my-oidc-group
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-artefact
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-market
  source:
    repoURL: https://github.com/mugdha-adhav/argocd-demo.git
    targetRevision: HEAD
    path: demo-artefact
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-store
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-artefact-wrapper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-market
  source:
    repoURL: https://github.com/mugdha-adhav/argocd-demo.git
    targetRevision: HEAD
    chart: demo-artefact-wrapper
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-wrapper
