apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels:
    app: demo-tag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-tag
  template:
    metadata:
      labels:
        app: demo-tag
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: nginx-service
